CREATE DATABASE 4thewords_prueba_leider_solano;
USE 4thewords_prueba_leider_solano;

CREATE TABLE IF NOT EXISTS provinces (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, 
    password VARCHAR(255) NOT NULL 
)
CREATE TABLE IF NOT EXISTS cantons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    province_id INT NOT NULL,
    CONSTRAINT fk_canton_province FOREIGN KEY (province_id) REFERENCES provinces(id)
);

CREATE TABLE IF NOT EXISTS districts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    canton_id INT NOT NULL,
    CONSTRAINT fk_district_canton FOREIGN KEY (canton_id) REFERENCES cantons(id)
);

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS legends (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(255) NOT NULL,
    category_id INT NOT NULL,
    legend_date DATETIME NOT NULL,
    image_url VARCHAR(255),
    cloudinary_public_id VARCHAR(255),
    district_id INT NOT NULL,
    
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_district FOREIGN KEY (district_id) REFERENCES districts(id)
);


INSERT INTO provinces(name) VALUES
('San José'),
('Alajuela'),
('Cartago'),
('Heredia'),
('Guanacaste'),
('Puntarenas'),
('Limón');


INSERT INTO cantons(name, province_id) VALUES
('San José', 1),
('Escazú', 1),
('Desamparados', 1),
('Puriscal', 1),
('Tarrazú',1),
('Aserrí', 1),
('Mora', 1),
('Goicoechea', 1),
('Santa Ana', 1),
('Alajuelita', 1),
('Vázquez de Coronado', 1),
('Acosta', 1),
('Tibás', 1),
('Moravia', 1),
('Montes de Oca', 1),
('Turrubares', 1),
('Dota', 1),
('Curridabat', 1),
('Pérez Zeledón', 1),
('León Cortés Castro',1),
('Alajuela', 2),
('San Ramón', 2),
('Grecia', 2),
('San Mateo', 2),
('Atenas', 2),
('Naranjo', 2),
('Palmares', 2),
('Poás', 2),
('Orotina', 2),
('San Carlos',2),
('Zarcero',2),
('Sarchí', 2),
('Upala', 2),
('Los Chiles', 2),
('Guatuso', 2),
('Río Cuarto', 2),
('Cartago', 3),
('Paraíso', 3),
('La Unión', 3),
('Jiménez', 3),
('Turrialba', 3),
('Alvarado', 3),
('Oreamuno', 3),
('El Guarco', 3),
('Heredia', 4),
('Barva', 4),
('Santo Domingo', 4),
('Santa Bárbara', 4),
('San Rafael', 4),
('San Isidro', 4),
('Belén', 4),
('Flores', 4),
('San Pablo', 4),
('Sarapiquí', 4),
('Liberia', 5),
('Nicoya', 5),
('Santa Cruz', 5),
('Bagaces', 5),
('Carrillo', 5),
('Cañas', 5),
('Abangares', 5),
('Tilarán', 5),
('Nandayure', 5),
('La Cruz', 5),
('Hojancha', 5),
('Puntarenas', 6),
('Esparza', 6),
('Buenos Aires', 6),
('Montes de Oro', 6),
('Osa', 6),
('Quepos', 6),
('Golfito', 6),
('Coto Brus', 6),
('Parrita', 6),
('Corredores', 6),
('Garabito', 6),
('Monteverde', 6),
('Puerto Jiménez', 6),
('Limon', 7),
('Pococí', 7),
('Siquirres', 7),
('Talamanca', 7),
('Matina', 7),
('Guácimo', 7);


INSERT INTO districts(name, canton_id) VALUES
('Carmen', 1),
('Merced', 1),
('Hospital', 1), 
('Catedral', 1),
('Zapote', 1),
('San Francisco de Dos Ríos', 1),
('Uruca', 1),
('Mata Redonda',1),
('Pavas', 1),
('Hatillo', 1),
('San Sebastián', 1),
-- Escazú (Canton 2)
('Escazú', 2),
('San Antonio', 2),
('San Rafael', 2),
-- Desamparados (Canton 3)
('Desamparados', 3),
('San Miguel', 3),
('San Juan de Dios', 3),
('San Rafael Arriba',3),
('San Antonio',3),
('Frailes', 3),
('Patarrá', 3),
('San Cristóbal', 3),
('Rosario', 3),
('Damas', 3),
('San Rafael Abajo', 3),  
('Gravilias', 3),
('Los Guido', 3),
-- Puriscal (Canton 4)
('Santiago', 4),
('Mercedes Sur', 4),
('Barbacoas', 4),
('Grifo Alto', 4),
('San Rafael', 4),
('Candelarita', 4),
('Desamparaditos', 4),
('San Antonio', 4),
('Chires', 4),
-- Tarrazú (Canton 5)
('San Marcos', 5),
('San Lorenzo', 5),
('San Carlos', 5),
-- Aserrí (Canton 6)
('Aserrí', 6),
('Tarbaca', 6),
('Vuelta de Jorco', 6),
('San Gabriel', 6),
('Legua', 6),
('Monterrey', 6),
('Salitrillos', 6),
-- Mora (Canton 7)
('Colón', 7),
('Guayabo', 7),
('Tabarcia', 7),
('Piedras Negras', 7),
('Picagres', 7),
('Jaris', 7),
('Quitirrisi', 7),
-- Goicoechea (Canton 8)
('Guadalupe', 8),
('San Francisco', 8),
('Calle Blancos', 8),
('Mata de Plátano', 8),
('Ipís', 8),
('Rancho Redondo', 8),
('Purral', 8),
-- Santa Ana (Canton 9)
('Santa Ana', 9),
('Salitral', 9),
('Pozos', 9),
('Uruca', 9),
('Piedades', 9),
('Brasil', 9),
-- Alajuelita (Canton 10)
('Alajuelita', 10),
('San Josecito',10),
('San Antonio', 10),
('Concepción', 10),
('Sucesión', 10),
('San Felipe', 10),
-- Vázquez de Coronado (Canton 11)
('San Isidro', 11),
('San Rafael', 11),
('Dulce Nombre de Jesús', 11),
('Patalillo', 11),
('Cascajal', 11),
-- Acosta (Canton 12)
('San Ignacio', 12),
('Palmichal', 12),
('Cangrejal', 12),
('Sabanillas', 12),
-- Tibás (Canton 13)
('San Juan', 13),
('Cinco Esquinas', 13),
('Anselmo Llorente', 13),
('León XIII', 13),
('Colima', 13),
-- Moravia (Canton 14)
('San Vicente', 14),
('San Jerónimo', 14),
('La Trinidad', 14),
-- Montes de Oca (Canton 15)
('San Pedro', 15),
('Sabanilla', 15),
('Mercedes', 15),
('San Rafael', 15),
-- Turrubares (Canton 16)
('San Pablo', 16),
('San Pedro', 16),
('San Juan de Mata', 16),
('San Luis', 16),
('Carara', 16),
-- Dota (Canton 17)
('Santa María', 17),
('Jardín', 17),
('Copey', 17),
-- Curridabat (Canton 18)
('Curridabat', 18),
('Granadilla', 18),
('Sánchez', 18),
('Tirrases', 18),
-- Pérez Zeledón (Canton 19)
('San Isidro de El General', 19),
('El General', 19),
('Daniel Flores', 19),
('Rivas', 19),
('San Pedro', 19),
('Platanares', 19),
('Pejibaye', 19),
('Cajón', 19),
('Barú', 19),
('Río Nuevo', 19),
('Paramo', 19),
('La Amistad', 19),
-- León Cortés Castro (Canton 20)
('San Pablo', 20),
('San Andrés', 20),
('Llano Bonito', 20),
('San Isidro', 20),
('Santa Cruz', 20),
('San Antonio', 20),
-- Alajuela (Canton 21)
('Alajuela', 21),
('San José', 21),
('Carrizal', 21),
('San Antonio', 21),
('Guácima', 21),
('San Isidro', 21),
('Sabanilla', 21),
('San Rafael', 21),
('Río Segundo', 21),
('Desamparados', 21),
('Turrúcares', 21),
('Tambor', 21),
('Sarapiquí', 21),
-- San Ramón (Canton 22)
('San Ramón', 22),
('Santiago', 22),
('San Juan', 22),
('Piedades Norte', 22),
('Piedades Sur', 22),
('San Rafael', 22),
('San Isidro', 22),
('Ángeles', 22),
('Alfaro', 22),
('Volio', 22),
('Concepción', 22),
('Zapotal', 22),
('Peñas Blancas', 22),
('San Lorenzo', 22),
-- Grecia (Canton 23)
('Grecia', 23),
('San Isidro', 23),
('San José', 23),
('San Roque', 23),
('Tacares', 23),
('Puente de Piedra', 23),
('Bolivar', 23),
-- San Mateo (Canton 24)
('San Mateo', 24),
('Desmonte', 24),
('Jesús María', 24),
('Labrador', 24),
-- Atenas (Canton 25)
('Atenas', 25),
('Jesús', 25),
('Mercedes', 25),
('San Isidro', 25),
('Concepción', 25),
('San José', 25),
('Santa Eulalia', 25),
('Escobal', 25),
-- Naranjo (Canton 26)
('Naranjo', 26),
('San Miguel', 26),
('San José', 26),
('Cirrí Sur', 26),
('San Jerónimo', 26),
('San Juan', 26),
('El Rosario', 26),
('Palmitos', 26),
-- Palmares (Canton 27)
('Palmares', 27),
('Zaragoza', 27),
('Buenos Aires', 27),
('Santiago', 27),
('Candelaria', 27),
('Esquipulas', 27),
('La Granja', 27),
-- Poás (Canton 28)
('San Pedro', 28),
('San Juan', 28),
('San Rafael', 28),
('Carrillos', 28),
('Sabana Redonda', 28),
-- Orotina (Canton 29)
('Orotina', 29),
('El Mastate', 29),
('Hacienda Vieja', 29),
('Coyolar', 29),
('La Ceiba', 29),
-- San Carlos (Canton 30)
('Quesada', 30),
('Florencia', 30),
('Buenavista', 30),
('Aguas Zarcas', 30),
('Venecia', 30),
('Pital', 30),
('La Fortuna', 30),
('La Tigra', 30),
('La Palmera', 30),
('Venado', 30),
('Cutris', 30),
('Monterrey', 30),
('Pocosol', 30),
-- Zarcero (Canton 31)
('Zarcero', 31),
('Laguna', 31),
('Tapesco', 31),
('Guadalupe', 31),
('Palmira', 31),
('Zapote', 31),
('Brisas', 31),
-- Sarchí (Canton 32)
('Sarchí Norte', 32),
('Sarchí Sur', 32),
('Toro Amarillo', 32),
('San Pedro', 32),
('Rodríguez', 32),
-- Upala (Canton 33)
('Upala', 33),
('Aguas Claras', 33),
('San José', 33),
('Bijagua', 33),
('Delicias', 33),
('Dos Ríos', 33),
('Yolillal', 33),
('Canalete', 33),
-- Los Chiles (Canton 34)
('Los Chiles', 34),
('Caño Negro', 34),
('El Amparo', 34),
('San Jorge', 34),
-- Guatuso (Canton 35)
('San Rafael', 35),
('Buenavista', 35),
('Cote', 35),
('Katira', 35),
-- Río Cuarto (Canton 36)
('Río Cuarto', 36),
('Santa Rita', 36),
('Santa Isabel', 36),
-- Cartago (Canton 37)
('Oriental', 37),
('Occidental', 37),
('Carmen', 37),
('San Nicolás', 37),
('Aguacaliente', 37),
('Guadalupe', 37),
('Corralillo', 37),
('Tierra Blanca', 37),
('Dulce Nombre', 37),
('Llano Grande', 37),
('Quebradilla', 37),
-- Paraíso (Canton 38)
('Paraíso', 38),
('Santiago', 38),
('Orosi', 38),
('Cachí', 38),
('Llanos de Santa Lucía', 38),
('Birrisito',38),
-- La Unión (Canton 39)
('Tres Ríos', 39),
('San Diego', 39),
('San Juan', 39),
('San Rafael', 39),
('Concepción', 39),
('Dulce Nombre', 39),
('San Ramón', 39),
('Río Azul', 39),
-- Jiménez (Canton 40)
('Juan Viñas', 40),
('Tucurrique', 40),
('Pejibaye', 40),
('La VIctoria', 40),
-- Turrialba (Canton 41)
('Turrialba', 41),
('La Suiza', 41),
('Peralta', 41),
('Santa Cruz', 41),
('Santa Teresita', 41),
('Pavones', 41),
('Tuis', 41),
('Tayutic', 41),
('Santa Rosa', 41),
('Tres Equis', 41),
('La Isabel', 41),
('Chirripó', 41),
-- Alvarado (Canton 42)
('Pacayas', 42),
('Cervantes', 42),
('Capellades', 42),
-- Oreamuno (Canton 43)
('San Rafael', 43),
('Cot', 43),
('Potrero Cerrado', 43),
('Cipreses', 43),
('Santa Rosa', 43),
-- El Guarco (Canton 44)
('El Tejar', 44),
('San Isidro', 44),
('Tobosi', 44),
('Patio de Agua', 44),
-- Heredia (Canton 45)
('Heredia', 45),
('Mercedes', 45),
('San Francisco', 45),
('Ulloa', 45),
('Varablanca', 45),
-- Barva (Canton 46)
('Barva', 46),
('San Pedro', 46),
('San Pablo', 46),
('San Roque', 46),
('Santa Lucía', 46),
('San José de la Montaña', 46),
-- Santo Domingo (Canton 47)
('Santo Domingo', 47),
('San Vicente', 47),
('San Miguel', 47),
('Paracito', 47),
('Santo Tomás', 47),
('Santa Rosa', 47),
('Tures', 47),
('Pará', 47),
-- Santa Bárbara (Canton 48)
('Santa Bárbara', 48),
('San Pedro', 48),
('San Juan', 48),
('Jesús', 48),
('Santo Domingo', 48),
('Purabá', 48),
-- San Rafael (Canton 49)
('San Rafael', 49),
('San Josecito', 49),
('Santiago', 49),
('Ángeles', 49),
('Concepción', 49),
-- San Isidro (Canton 50)
('San Isidro', 50),
('San José', 50),
('Concepción', 50),
('San Francisco', 50),
-- Belén (Canton 51)
('San Antonio', 51),
('La Ribera', 51),
('Asunción', 51),
-- Flores (Canton 52)
('San Joaquín', 52),
('Barrantes', 52),
('Llorente', 52),
-- San Pablo (Canton 53)
('San Pablo', 53),
('Rincón de Sabanilla', 53),
-- Sarapiquí (Canton 54)
('Puerto Viejo', 54),
('La Virgen', 54),
('Las Horquetas', 54),
('Llanuras del Gaspar', 54),
('Cureña', 54),
-- Liberia (Canton 55)
('Liberia', 55),
('Cañas Dulces', 55),
('Mayorga', 55),
('Nacascolo', 55),
('Curubandé', 55),
-- Nicoya (Canton 56)
('Nicoya', 56),
('Mansión', 56),
('San Antonio', 56),
('Quebrada Honda', 56),
('Sámara', 56),
('Nosara', 56),
('Belén de Nosarita', 56),
-- Santa Cruz (Canton 57)
('Santa Cruz', 57),
('Bolsón', 57),
('Veintisiete de Abril', 57),
('Tempate', 57),
('Cartagena', 57),
('Cuajiniquil', 57),
('Diriá', 57),
('Cabo Velas', 57),
('Tamarindo', 57),
-- Bagaces (Canton 58)
('Bagaces', 58),
('La Fortuna', 58),
('Mogote', 58),
('Río Naranjo', 58),
-- Carrillo (Canton 59)
('Filadelfia', 59),
('Palmira', 59),
('Sardinal', 59),
('Belén', 59),
-- Cañas (Canton 60)
('Cañas', 60),
('Palmira', 60),
('San Miguel', 60),
('Bebedero', 60),
('Porozal', 60),
-- Abangares (Canton 61)
('Las Juntas', 61),
('Sierra', 61),
('San Juan', 61),
('Colorado', 61),
-- Tilarán (Canton 62)
('Tilarán', 62),
('Quebrada Grande', 62),
('Tronadora', 62),
('Santa Rosa', 62),
('Líbano', 62),
('Tierras Morenas', 62),
('Arenal', 62),
('Cabeceras',62),
-- Nandayure (Canton 63)
('Carmona', 63),
('Santa Rita', 63),
('Zapotal', 63),
('San Pablo', 63),
('Porvenir', 63),
('Bejuco', 63),
-- La Cruz (Canton 64)
('La Cruz', 64),
('Santa Cecilia', 64),
('La Garita', 64),
('Santa Elena', 64),
-- Hojancha (Canton 65)
('Hojancha', 65),
('Monte Romo', 65),
('Puerto Carrillo', 65),
('Huacas', 65),
('Matambú', 65),
-- Puntarenas (Canton 66)
('Puntarenas', 66),
('Pitahaya', 66),
('Chomes',66),
('Lepanto', 66),
('Paquera', 66),
('Manzanillo', 66),
('Guacimal', 66),
('Barranca', 66),
('Isla del Coco', 66),
('Cóbano', 66),
('Chacarita', 66),
('Chira', 66),
('Acapulco', 66),
('El Roble', 66),
('Arancibia', 66),
-- Esparza (Canton 67)
('Espíritu Santo', 67),
('San Juan Grande', 67),
('Macacona', 67),
('San Rafael', 67),
('San Jerónimo', 67),
('Caldera', 67),
-- Buenos Aires (Canton 68)
('Buenos Aires', 68),
('Volcán', 68),
('Potrero Grande', 68),
('Boruca', 68),
('Pilas', 68),
('Colinas', 68),
('Chánguena', 68),
('Bioley', 68),
('Brunka', 68),
-- Montes de Oro (Canton 69)
('Miramar', 69),
('La Unión', 69),
('San Isidro', 69),
-- Osa (Canton 70)
('Puerto Cortés', 70),
('Palmar', 70),
('Sierpe', 70),
('Bahía Ballena', 70),
('Piedras Blancas', 70),
('Bahía Drake', 70),
-- Quepos (Canton 71)
('Quepos', 71),
('Savegre', 71),
('Naranjito', 71),
-- Golfito (Canton 72)
('Golfito', 72),
('Guaycará', 72),
('Pavón', 72),
-- Coto Brus (Canton 73)
('San Vito', 73),
('Sabalito', 73),
('Aguabuena', 73),
('Limoncito', 73),
('Pittier', 73),
('Gutiérrez Braun', 73),
-- Parrita (Canton 74)
('Parrita', 74),
-- Corredores (Canton 75)
('Corredor', 75),
('La Cuesta', 75),
('Canoas', 75),
('Laurel', 75),
-- Garabito (Canton 76)
('Jacó', 76),
('Tárcoles', 76),
-- Monteverde (Canton 77)
('Monteverde', 77),
-- Puerto Jiménez (Canton 78)
('Puerto Jiménez', 78),
-- Limón (Canton 79)
('Limón', 79),
('Valle La Estrella', 79),
('Río Blanco', 79),
('Matama', 79),
-- Pococí (Canton 80)
('Guápiles', 80),
('Jiménez', 80),
('Rita', 80),
('Roxana', 80),
('Cariari', 80),
('Colorado', 80),
('La Colonia', 80),
-- Siquirres (Canton 81)
('Siquirres', 81),
('Pacuarito', 81),
('Florida', 81),
('Cairo', 81),
('Alegría', 81),
('Reventazón', 81),
-- Talamanca (Canton 82)
('Bratsi', 82),
('Sixaola', 82),
('Cahuita', 82),
('Telire', 82),
-- Matina (Canton 83)
('Matina', 83),
('Batán', 83),
('Carrandí', 83),
-- Guácimo (Canton 84)
('Guácimo', 84),
('Mercedes', 84),
('Pocora', 84),
('Río Jiménez', 84),
('Duacarí', 84);

INSERT INTO categories(name) VALUES
('Terror'),
('Criatura mítica'),
('Religiosa'),
('Moraleja'),
('Naturaleza'),
('Historica'),
('Popular');

INSERT INTO legends (name, description, category_id, legend_date, image_url, cloudinary_public_id, district_id) VALUES
('La llorona', 'Mujer que llora por sus hijos muertos, suele escucharse cerca de ríos en las noches.', 1, '2025-04-04 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751670663/La_llorona_hrqbcl.jpg', 'legendsImages/La_llorona_hrqbcl', 25),
('El Cadejos', 'Perro negro (bueno o malo) que acompaña a viajeros, castiga o protege según su alma.', 2, '2025-03-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672111/El_Cadejos_vt84zd.jpg', 'legendsImages/El_Cadejos_vt84zd', 293),
('La Tulevieja', 'Mujer con cabeza de rana y cuerpo hinchado que castiga hombres lujuriosos.', 4, '2025-02-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672067/La_Tulevieja_g1vdpd.jpg', 'legendsImages/La_Tulevieja_g1vdpd', 252),
('La Segua', '	Mujer hermosa que se convierte en monstruo cuando el hombre la sigue con deseo.', 1, '2025-01-17 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672092/La_Segua_o8m0te.jpg', 'legendsImages/La_Segua_o8m0te', 125),
('El Padre sin Cabeza', 'Cura fantasma que vaga sin cabeza por iglesias o cementerios.', 3, '2025-02-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672111/El_Padre_sin_Cabeza_qn18t6.jpg', 'legendsImages/El_Padre_sin_Cabeza_qn18t6', 4),
('El Sisimiqui', 'Un ogro con cara de hombre y cuerpo de mono, cubierto de espeso vello. Se dice que rapta mujeres, especialmente en sus noches de bodas.', 2, '2025-06-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672110/El_Sisimiqui_nizhq5.jpg', 'legendsImages/El_Sisimiqui_nizhq5', 292),
('La Mona', 'Mujer transformada en simio, asociada con brujería y venganza.', 2, '2024-12-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672097/La_Mona_jfxrre.jpg', 'legendsImages/La_Mona_jfxrre', 403),
('El Micomalo', 'Criatura peluda que habita zonas rurales y se lleva niños desobedientes.', 4, '2024-12-17 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672130/El_Micomalo_x4bcow.jpg', 'legendsImages/El_Micomalo_x4bcow', 361),
('La Carreta sin Bueyes', '	Carreta fantasmal sin bueyes, símbolo de muerte inminente.', 7, '2025-05-10 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672214/La_Carreta_sin_bueyes_s027qi.jpg', 'legendsImages/La_Carreta_sin_bueyes_s027qi', 175),
('La Bruja Zárate', 'Mujer con poderes sobrenaturales que se transforma en ave y ronda los techos.', 2, '2025-01-22 00:00:00', 'https://res.cloudinary.com/dpqxu23gd/image/upload/v1751672112/La_Brija_Z%C3%A1rate_oczi4u.jpg', 'legendsImages/La_Brija_Z%C3%A1rate_oczi4u', 40);










